'\" Copyright (C) 2017 AT&T Intellectual Property. All rights reserved. 
'\"
'\" Licensed under the Apache License, Version 2.0 (the "License");
'\" you may not use this code except in compliance
'\" with the License. You may obtain a copy of the License
'\" at http://www.apache.org/licenses/LICENSE-2.0
'\" 
'\" Unless required by applicable law or agreed to in writing, software 
'\" distributed under the License is distributed on an "AS IS" BASIS, 
'\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
'\" implied. See the License for the specific language governing 
'\" permissions and limitations under the License.
.TH show_pg_stat_database_conflicts 1PG {{DATE}} OpenECOMP OpenECOMP
.SH NAME
show_pg_stat_database_conflicts - convenience program to extract info from the database
.SH SYNOPSIS
show_pg_stat_database_conflicts
.SH DESCRIPTION
show_pg_stat_database_conflicts is a convenience program to extract the pg_stat_database_conflicts information from the database.
