all:

build:
	cd cdf-util/src/main/java && $(MAKE) build
	cd cdf-prop-value/src/main/java && $(MAKE) build

javadocs:
	cd cdf-util/src/main/java && $(MAKE) javadocs
	cd cdf-prop-value/src/main/java && $(MAKE) javadocs

clean:
	cd cdf-util/src/main/java && $(MAKE) clean
	cd cdf-prop-value/src/main/java && $(MAKE) clean
